name: Destroy Terraform Module on Branch Delete

on:
  delete:
    branches:
      - 'code_t*'  # Prati samo feature branch-eve, npr. code_t123

jobs:
  destroy:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    env:
      DELETED_BRANCH: ${{ github.event.ref }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # ili tvoja verzija

      - name: Generate Dynamic Terraform File for Destroy
        run: |
          mkdir -p ./dynamic_tf
          sed "s/\${branch}/${DELETED_BRANCH}/g" templates/module.tf.tpl > dynamic_tf/main.tf

      - name: Terraform Init
        working-directory: ./dynamic_tf
        run: terraform init

      - name: Terraform Destroy Target Module
        working-directory: ./dynamic_tf
        run: terraform destroy -auto-approve -target=module.${DELETED_BRANCH}

